from .patient_management import (
    patient_management_mcp,
    list_patients,
    get_patient_details,
    add_patient,
    update_patient,
    deactivate_patient,
    activate_patient,
    send_phr_invite,
    upload_patient_id,
    upload_patient_photo,
    delete_patient_photo,
    list_quick_notes,
    add_quick_note,
    edit_quick_note,
    delete_quick_note,
    get_recalls,
    add_recall,
    add_supplement,
    list_supplements,
    edit_supplement,
    add_allergy,
    get_allergies,
    edit_allergy,
    delete_allergy,
    add_medication,
    list_medications,
    edit_medication,
    delete_medication,
    list_lab_results,
    get_detailed_lab_result,
    add_lab_result,
    add_diagnosis,
    get_diagnoses,
    update_diagnosis,
    delete_diagnosis,
    add_vitals,
)
from .encounter import (
    encounter_mcp,
    list_encounters,
    get_encounter_details,
    create_encounter,
    save_encounter,
)
from .practice_information import (
    practice_information_mcp,
    list_facilities,
    list_members,
    list_available_vitals_for_practice,
)

__all__ = [
    # MCP instances
    "patient_management_mcp",
    "encounter_mcp",
    "practice_information_mcp",
    # Patient management tools
    "list_patients",
    "get_patient_details",
    "add_patient",
    "update_patient",
    "deactivate_patient",
    "activate_patient",
    "send_phr_invite",
    "upload_patient_id",
    "upload_patient_photo",
    "delete_patient_photo",
    "list_quick_notes",
    "add_quick_note",
    "edit_quick_note",
    "delete_quick_note",
    "get_recalls",
    "add_recall",
    "add_supplement",
    "list_supplements",
    "edit_supplement",
    "add_allergy",
    "get_allergies",
    "edit_allergy",
    "delete_allergy",
    "add_medication",
    "list_medications",
    "edit_medication",
    "delete_medication",
    "list_lab_results",
    "get_detailed_lab_result",
    "add_lab_result",
    "add_diagnosis",
    "get_diagnoses",
    "update_diagnosis",
    "delete_diagnosis",
    "add_vitals",
    # Encounter tools
    "list_encounters",
    "get_encounter_details",
    "create_encounter",
    "save_encounter",
    # Practice information tools
    "list_facilities",
    "list_members",
    "list_available_vitals_for_practice",
]

